plugins {
    id 'java'
    id 'application'
}

group = 'co.icesi.project'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.apache.commons:commons-csv:1.10.0'
    implementation 'org.apache.poi:poi-ooxml:5.2.5'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    implementation 'org.apache.logging.log4j:log4j-to-slf4j:2.23.1'
    implementation 'org.slf4j:slf4j-simple:2.0.13'
}

application {
    mainClass = 'co.icesi.project.app.Main'
}

test {
    useJUnitPlatform()
}

subprojects {
    repositories {
        mavenCentral()
    }

    plugins.withType(JavaPlugin) {
        tasks.withType(JavaCompile).configureEach {
            options.release = 11
        }
    }
}
