//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

/** @hidden */
public class _BrokerPrxI extends com.zeroc.Ice._ObjectPrxI implements BrokerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
