//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

public class BusEvent implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public String source;

    public String destination;

    public String messageType;

    public String timestamp;

    public String detail;

    public BusEvent()
    {
        this.source = "";
        this.destination = "";
        this.messageType = "";
        this.timestamp = "";
        this.detail = "";
    }

    public BusEvent(String source, String destination, String messageType, String timestamp, String detail)
    {
        this.source = source;
        this.destination = destination;
        this.messageType = messageType;
        this.timestamp = timestamp;
        this.detail = detail;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        BusEvent r = null;
        if(rhs instanceof BusEvent)
        {
            r = (BusEvent)rhs;
        }

        if(r != null)
        {
            if(this.source != r.source)
            {
                if(this.source == null || r.source == null || !this.source.equals(r.source))
                {
                    return false;
                }
            }
            if(this.destination != r.destination)
            {
                if(this.destination == null || r.destination == null || !this.destination.equals(r.destination))
                {
                    return false;
                }
            }
            if(this.messageType != r.messageType)
            {
                if(this.messageType == null || r.messageType == null || !this.messageType.equals(r.messageType))
                {
                    return false;
                }
            }
            if(this.timestamp != r.timestamp)
            {
                if(this.timestamp == null || r.timestamp == null || !this.timestamp.equals(r.timestamp))
                {
                    return false;
                }
            }
            if(this.detail != r.detail)
            {
                if(this.detail == null || r.detail == null || !this.detail.equals(r.detail))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::sitmmio::v3::slice::BusEvent");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, source);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destination);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, messageType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, timestamp);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, detail);
        return h_;
    }

    public BusEvent clone()
    {
        BusEvent c = null;
        try
        {
            c = (BusEvent)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.source);
        ostr.writeString(this.destination);
        ostr.writeString(this.messageType);
        ostr.writeString(this.timestamp);
        ostr.writeString(this.detail);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.source = istr.readString();
        this.destination = istr.readString();
        this.messageType = istr.readString();
        this.timestamp = istr.readString();
        this.detail = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, BusEvent v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public BusEvent ice_read(com.zeroc.Ice.InputStream istr)
    {
        BusEvent v = new BusEvent();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<BusEvent> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, BusEvent v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<BusEvent> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(BusEvent.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final BusEvent _nullMarshalValue = new BusEvent();

    /** @hidden */
    public static final long serialVersionUID = -1475799404L;
}
