//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

public interface MasterPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerWorker(String workerId, WorkerPrx worker)
    {
        registerWorker(workerId, worker, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerWorker(String workerId, WorkerPrx worker, java.util.Map<String, String> context)
    {
        _iceI_registerWorkerAsync(workerId, worker, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(String workerId, WorkerPrx worker)
    {
        return _iceI_registerWorkerAsync(workerId, worker, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(String workerId, WorkerPrx worker, java.util.Map<String, String> context)
    {
        return _iceI_registerWorkerAsync(workerId, worker, context, false);
    }

    /**
     * @hidden
     * @param iceP_workerId -
     * @param iceP_worker -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerWorkerAsync(String iceP_workerId, WorkerPrx iceP_worker, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_workerId);
                     ostr.writeProxy(iceP_worker);
                 }, null);
        return f;
    }

    default void unregisterWorker(String workerId)
    {
        unregisterWorker(workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unregisterWorker(String workerId, java.util.Map<String, String> context)
    {
        _iceI_unregisterWorkerAsync(workerId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(String workerId)
    {
        return _iceI_unregisterWorkerAsync(workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unregisterWorkerAsync(String workerId, java.util.Map<String, String> context)
    {
        return _iceI_unregisterWorkerAsync(workerId, context, false);
    }

    /**
     * @hidden
     * @param iceP_workerId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unregisterWorkerAsync(String iceP_workerId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unregisterWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_workerId);
                 }, null);
        return f;
    }

    default SpeedResult execute(SpeedTask task)
    {
        return execute(task, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default SpeedResult execute(SpeedTask task, java.util.Map<String, String> context)
    {
        return _iceI_executeAsync(task, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<SpeedResult> executeAsync(SpeedTask task)
    {
        return _iceI_executeAsync(task, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<SpeedResult> executeAsync(SpeedTask task, java.util.Map<String, String> context)
    {
        return _iceI_executeAsync(task, context, false);
    }

    /**
     * @hidden
     * @param iceP_task -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<SpeedResult> _iceI_executeAsync(SpeedTask iceP_task, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<SpeedResult> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "execute", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     SpeedTask.ice_write(ostr, iceP_task);
                 }, istr -> {
                     SpeedResult ret;
                     ret = SpeedResult.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default String[] activeWorkers()
    {
        return activeWorkers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String[] activeWorkers(java.util.Map<String, String> context)
    {
        return _iceI_activeWorkersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<String[]> activeWorkersAsync()
    {
        return _iceI_activeWorkersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<String[]> activeWorkersAsync(java.util.Map<String, String> context)
    {
        return _iceI_activeWorkersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<String[]> _iceI_activeWorkersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<String[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "activeWorkers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String[] ret;
                     ret = istr.readStringSeq();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MasterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MasterPrx.class, _MasterPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MasterPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MasterPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MasterPrx ice_adapterId(String newAdapterId)
    {
        return (MasterPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MasterPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MasterPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MasterPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MasterPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in milliseconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MasterPrx ice_invocationTimeout(int newTimeout)
    {
        return (MasterPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MasterPrx ice_connectionCached(boolean newCache)
    {
        return (MasterPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MasterPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MasterPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterPrx ice_secure(boolean b)
    {
        return (MasterPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MasterPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MasterPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterPrx ice_preferSecure(boolean b)
    {
        return (MasterPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MasterPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MasterPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MasterPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MasterPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MasterPrx ice_collocationOptimized(boolean b)
    {
        return (MasterPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MasterPrx ice_twoway()
    {
        return (MasterPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MasterPrx ice_oneway()
    {
        return (MasterPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MasterPrx ice_batchOneway()
    {
        return (MasterPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MasterPrx ice_datagram()
    {
        return (MasterPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MasterPrx ice_batchDatagram()
    {
        return (MasterPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MasterPrx ice_compress(boolean co)
    {
        return (MasterPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MasterPrx ice_timeout(int t)
    {
        return (MasterPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MasterPrx ice_connectionId(String connectionId)
    {
        return (MasterPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MasterPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MasterPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::sitmmio::v3::slice::Master";
    }
}
