//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

public class SpeedResult implements java.lang.Cloneable,
                                    java.io.Serializable
{
    public String taskId;

    public boolean success;

    public String message;

    public String outputPath;

    public int records;

    public long elapsedMs;

    public SpeedStat[] stats;

    public SpeedResult()
    {
        this.taskId = "";
        this.message = "";
        this.outputPath = "";
    }

    public SpeedResult(String taskId, boolean success, String message, String outputPath, int records, long elapsedMs, SpeedStat[] stats)
    {
        this.taskId = taskId;
        this.success = success;
        this.message = message;
        this.outputPath = outputPath;
        this.records = records;
        this.elapsedMs = elapsedMs;
        this.stats = stats;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SpeedResult r = null;
        if(rhs instanceof SpeedResult)
        {
            r = (SpeedResult)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.success != r.success)
            {
                return false;
            }
            if(this.message != r.message)
            {
                if(this.message == null || r.message == null || !this.message.equals(r.message))
                {
                    return false;
                }
            }
            if(this.outputPath != r.outputPath)
            {
                if(this.outputPath == null || r.outputPath == null || !this.outputPath.equals(r.outputPath))
                {
                    return false;
                }
            }
            if(this.records != r.records)
            {
                return false;
            }
            if(this.elapsedMs != r.elapsedMs)
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.stats, r.stats))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::sitmmio::v3::slice::SpeedResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, success);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, message);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, outputPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, records);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, elapsedMs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stats);
        return h_;
    }

    public SpeedResult clone()
    {
        SpeedResult c = null;
        try
        {
            c = (SpeedResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.taskId);
        ostr.writeBool(this.success);
        ostr.writeString(this.message);
        ostr.writeString(this.outputPath);
        ostr.writeInt(this.records);
        ostr.writeLong(this.elapsedMs);
        SpeedStatSeqHelper.write(ostr, this.stats);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readString();
        this.success = istr.readBool();
        this.message = istr.readString();
        this.outputPath = istr.readString();
        this.records = istr.readInt();
        this.elapsedMs = istr.readLong();
        this.stats = SpeedStatSeqHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SpeedResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SpeedResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        SpeedResult v = new SpeedResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SpeedResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SpeedResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SpeedResult _nullMarshalValue = new SpeedResult();

    /** @hidden */
    public static final long serialVersionUID = -1407966386L;
}
