//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

public class SpeedTask implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public String taskId;

    public String datagramsPath;

    public String routesPath;

    public String outputPath;

    public int maxRows;

    public int partitionIndex;

    public int partitionCount;

    public SpeedTask()
    {
        this.taskId = "";
        this.datagramsPath = "";
        this.routesPath = "";
        this.outputPath = "";
    }

    public SpeedTask(String taskId, String datagramsPath, String routesPath, String outputPath, int maxRows, int partitionIndex, int partitionCount)
    {
        this.taskId = taskId;
        this.datagramsPath = datagramsPath;
        this.routesPath = routesPath;
        this.outputPath = outputPath;
        this.maxRows = maxRows;
        this.partitionIndex = partitionIndex;
        this.partitionCount = partitionCount;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SpeedTask r = null;
        if(rhs instanceof SpeedTask)
        {
            r = (SpeedTask)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                if(this.taskId == null || r.taskId == null || !this.taskId.equals(r.taskId))
                {
                    return false;
                }
            }
            if(this.datagramsPath != r.datagramsPath)
            {
                if(this.datagramsPath == null || r.datagramsPath == null || !this.datagramsPath.equals(r.datagramsPath))
                {
                    return false;
                }
            }
            if(this.routesPath != r.routesPath)
            {
                if(this.routesPath == null || r.routesPath == null || !this.routesPath.equals(r.routesPath))
                {
                    return false;
                }
            }
            if(this.outputPath != r.outputPath)
            {
                if(this.outputPath == null || r.outputPath == null || !this.outputPath.equals(r.outputPath))
                {
                    return false;
                }
            }
            if(this.maxRows != r.maxRows)
            {
                return false;
            }
            if(this.partitionIndex != r.partitionIndex)
            {
                return false;
            }
            if(this.partitionCount != r.partitionCount)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::sitmmio::v3::slice::SpeedTask");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, datagramsPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, routesPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, outputPath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, maxRows);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, partitionIndex);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, partitionCount);
        return h_;
    }

    public SpeedTask clone()
    {
        SpeedTask c = null;
        try
        {
            c = (SpeedTask)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.taskId);
        ostr.writeString(this.datagramsPath);
        ostr.writeString(this.routesPath);
        ostr.writeString(this.outputPath);
        ostr.writeInt(this.maxRows);
        ostr.writeInt(this.partitionIndex);
        ostr.writeInt(this.partitionCount);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readString();
        this.datagramsPath = istr.readString();
        this.routesPath = istr.readString();
        this.outputPath = istr.readString();
        this.maxRows = istr.readInt();
        this.partitionIndex = istr.readInt();
        this.partitionCount = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SpeedTask v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SpeedTask ice_read(com.zeroc.Ice.InputStream istr)
    {
        SpeedTask v = new SpeedTask();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedTask> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedTask v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SpeedTask> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SpeedTask.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SpeedTask _nullMarshalValue = new SpeedTask();

    /** @hidden */
    public static final long serialVersionUID = 283439881L;
}
