//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

/**
 * Helper class for marshaling/unmarshaling SpeedStatSeq.
 **/
public final class SpeedStatSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, SpeedStat[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                SpeedStat.ice_write(ostr, v[i0]);
            }
        }
    }

    public static SpeedStat[] read(com.zeroc.Ice.InputStream istr)
    {
        final SpeedStat[] v;
        final int len0 = istr.readAndCheckSeqSize(21);
        v = new SpeedStat[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = SpeedStat.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedStat[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedStat[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            SpeedStatSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<SpeedStat[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            SpeedStat[] v;
            v = SpeedStatSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
