//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.11
//
// <auto-generated>
//
// Generated from file `SitmMio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package sitmmio.v3.slice;

public class SpeedStat implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int lineId;

    public String month;

    public long count;

    public double sum;

    public SpeedStat()
    {
        this.month = "";
    }

    public SpeedStat(int lineId, String month, long count, double sum)
    {
        this.lineId = lineId;
        this.month = month;
        this.count = count;
        this.sum = sum;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        SpeedStat r = null;
        if(rhs instanceof SpeedStat)
        {
            r = (SpeedStat)rhs;
        }

        if(r != null)
        {
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.month != r.month)
            {
                if(this.month == null || r.month == null || !this.month.equals(r.month))
                {
                    return false;
                }
            }
            if(this.count != r.count)
            {
                return false;
            }
            if(this.sum != r.sum)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::sitmmio::v3::slice::SpeedStat");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, month);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, count);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sum);
        return h_;
    }

    public SpeedStat clone()
    {
        SpeedStat c = null;
        try
        {
            c = (SpeedStat)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.lineId);
        ostr.writeString(this.month);
        ostr.writeLong(this.count);
        ostr.writeDouble(this.sum);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineId = istr.readInt();
        this.month = istr.readString();
        this.count = istr.readLong();
        this.sum = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, SpeedStat v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public SpeedStat ice_read(com.zeroc.Ice.InputStream istr)
    {
        SpeedStat v = new SpeedStat();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<SpeedStat> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, SpeedStat v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<SpeedStat> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(SpeedStat.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final SpeedStat _nullMarshalValue = new SpeedStat();

    /** @hidden */
    public static final long serialVersionUID = 1026216472L;
}
